{
    "openapi":"3.0.0",
    
    "paths":{
       "/":{
          "get":{
             "operationId":"AppController_getHello",
             "parameters":[
                
             ],
             "responses":{
                "200":{
                   "description":""
                }
             }
          }
       },
       "/cat":{
          "post":{
             "operationId":"CatController_create",
             "parameters":[
                
             ],
             "requestBody":{
                "required":true,
                "content":{
                   "application/json":{
                      "schema":{
                         "$ref":"#/components/schemas/CreateCatDto"
                      }
                   }
                }
             },
             "responses":{
                "201":{
                   "description":""
                }
             }
          },
          "get":{
             "operationId":"CatController_findAll",
             "parameters":[
                
             ],
             "responses":{
                "200":{
                   "description":""
                }
             }
          }
       },
       "/cat/{id}":{
          "get":{
             "operationId":"CatController_findOne",
             "parameters":[
                {
                   "name":"id",
                   "required":true,
                   "in":"path",
                   "schema":{
                      "type":"string"
                   }
                }
             ],
             "responses":{
                "200":{
                   "description":""
                }
             }
          },
          "patch":{
             "operationId":"CatController_update",
             "parameters":[
                {
                   "name":"id",
                   "required":true,
                   "in":"path",
                   "schema":{
                      "type":"string"
                   }
                }
             ],
             "requestBody":{
                "required":true,
                "content":{
                   "application/json":{
                      "schema":{
                         "$ref":"#/components/schemas/UpdateCatDto"
                      }
                   }
                }
             },
             "responses":{
                "200":{
                   "description":""
                }
             }
          },
          "delete":{
             "operationId":"CatController_remove",
             "parameters":[
                {
                   "name":"id",
                   "required":true,
                   "in":"path",
                   "schema":{
                      "type":"string"
                   }
                }
             ],
             "responses":{
                "200":{
                   "description":""
                }
             }
          }
       }
    },
    "info":{
       "title":"Cats example",
       "description":"The cats API description",
       "version":"1.0",
       "contact":{
          
       }
    },
    "tags":[
       {
          "name":"cats",
          "description":""
       }
    ],
    "servers":[
        {
            
        }
    ],
    "components":{
       "schemas":{
          "CreateCatDto":{
             "type":"object",
             "properties":{
                "name":{
                   "type":"string"
                },
                "age":{
                   "type":"number"
                },
                "breed":{
                   "type":"string"
                }
             },
             "required":[
                "name",
                "age",
                "breed"
             ]
          },
          "UpdateCatDto":{
             "type":"object",
             "properties":{
                
             }
          }
       }
    }
 }
